/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SCA.GUI;

import SCA.Dao.EmployeesDao;
import SCA.POJO.Employees;
import SCA.POJO.UserProfile;
import SCA.Utility.SlipGenerator;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankitjain
 */
public class ManageSalaryFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    DefaultTableModel model;
    List<Employees> list;
    public ManageSalaryFrame() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel)jTable.getModel();
        loadData();
        //txtlabel.setText("Welcome "+UserProfile.getUsername());
        
    }
    
    public void loadData()
    {
        try {
            list=EmployeesDao.getDetails();
            if(list.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"No Records Found");
                return;
            }
              Object[] rows=new Object[5];
        DefaultTableModel model=(DefaultTableModel)jTable.getModel();
        for(Employees emp:list)
        {
           rows[0]=emp.getEmp_id();
           rows[1]=emp.getName();
           rows[2]=emp.getContact();
           rows[3]=emp.getMail_id();
           rows[4]=emp.getSalary();
           

           model.addRow(rows);
        }
     
     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"DB Error!!");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        year = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        generateSalaryBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        month = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        year.setBackground(new java.awt.Color(173, 192, 234));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 160, 30));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 150, -1));

        generateSalaryBtn.setText("Generate Salary Slip");
        generateSalaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSalaryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(generateSalaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 370, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 880, 20));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp_Id", "Name", "Phone", "Mail Id", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 162, 840, 450));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setText("Salary Month -");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 180, 30));

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(quitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 640, 160, -1));

        month.setBackground(new java.awt.Color(173, 192, 234));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "JulyA", "ugust", "September", "October", "November", "December" }));
        month.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminOptionsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void generateSalaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSalaryBtnActionPerformed
        // TODO add your handling code here:
        String mon_year=(String)month.getSelectedItem()+"_"+(String)year.getSelectedItem();
        if(list.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"No Available Record","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for(Employees emp2:list)
        {
            SlipGenerator.generateSlip(emp2,mon_year);
        }
        
        JOptionPane.showMessageDialog(null,"Salary Slip generated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        return;

    }//GEN-LAST:event_generateSalaryBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSalaryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton generateSalaryBtn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JButton quitBtn;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
